# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MappingUrlTimestamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('md5', models.TextField()),
                ('filename', models.TextField()),
                ('indexed_timestamp', models.IntegerField()),
                ('status_code', models.IntegerField()),
            ],
        ),
    ]
